feat: Add project page gf-86
BinaryStudioAcademy/bsa-2024-gitfit pull request #109
Opened 2024-08-28 20:21 UTC by HoroshkoMykhailo

Summary:

- Added a new route to handle navigation to the Project page.
- Developed a Project page component that displays the project title and description. But it has not yet been linked to the project list because the project list feature is not implemented.

![image](https://github.com/user-attachments/assets/3482bef7-4d85-4335-846d-3319ae67d220)

2024-08-29 12:03 UTC, perekotypole commented on packages/shared/src/modules/projects/libs/enums/projects-api-path.enum.ts
> +	BY_ID: "/:id",
We used '$ID' instead of 'BY_ID before'. I suppose it's better to keep it unified

2024-08-29 17:25 UTC, liza-veis commented on apps/backend/src/db/migrations/20240823114259_add_projects_table.ts
> -	DESCRIPTION: 50,
Agree, and this should be made in a separate migration, otherwise this changes won't apply

2024-08-30 08:37 UTC, liza-veis requested changes

2024-08-30 08:37 UTC, liza-veis commented on apps/backend/src/db/migrations/20240829201429_change_description_type.ts
> +	UP_DESCRIPTION: 1000,
```suggestion
	DESCRIPTION_PREVIOUS: 50,
	DESCRIPTION: 1000,
```

2024-08-30 08:37 UTC, liza-veis commented on apps/backend/src/modules/projects/project.entity.ts
> +import { type ProjectResponseDto } from "./libs/types/types.js";
let's use ProjectGetAllItemResponseDto here. It should be ProjectGetByIdResponseDto, but for now these types are the same, so let's use it
```suggestion
import { type ProjectGetAllItemResponseDto } from "./libs/types/types.js";
```

2024-08-30 08:37 UTC, liza-veis commented on apps/backend/src/modules/projects/project.service.ts
> +	public async find(id: number): Promise<ProjectResponseDto> {
same as above
```suggestion
	public async find(id: number): Promise<ProjectGetAllItemResponseDto> {
```

2024-08-30 08:37 UTC, liza-veis commented on apps/frontend/src/pages/project/project.tsx
> +					) : (
too many conditions, let's use if and return for isRejected case

2024-08-30 08:37 UTC, liza-veis commented on apps/frontend/src/pages/projects/components/project-card/project-card.tsx
> +	project: ProjectResponseDto;
we don't need ProjectResponseDto
```suggestion
	project: ProjectGetAllItemResponseDto;
```

2024-08-30 08:37 UTC, liza-veis commented on packages/shared/src/modules/projects/libs/types/project-response-dto.type.ts
> +type ProjectResponseDto = {
```suggestion
type ProjectGetByIdResponseDto = {
```

2024-08-30 08:37 UTC, liza-veis commented on apps/frontend/src/pages/project/project.tsx
> +	const { id: projectId } = useParams<ProjectFindRequestDto>();
let's define type for useParams inline
```suggestion
	const { id: projectId } = useParams<{ id: string }>();
```

2024-08-30 08:37 UTC, liza-veis commented on apps/frontend/src/pages/projects/components/project-card/project-card.tsx
> +			to={AppRoute.PROJECT.replace(":id", project.id.toString())}
use configureString helper

2024-08-30 10:57 UTC, what1s1ove approved these changes
Looking good after Lisa's request changes

2024-08-30 18:16 UTC, liza-veis requested changes

2024-08-30 18:16 UTC, liza-veis commented on apps/frontend/src/modules/projects/projects-api.ts
> +		payload: ProjectFindRequestDto,
rename it to ProjectGetByIdRequestDto
```suggestion
		payload: ProjectGetByIdRequestDto,
```

2024-08-30 18:16 UTC, liza-veis commented on apps/frontend/src/modules/projects/slices/project.slice.ts
> +			state.dataStatus = DataStatus.PENDING;
Let's use dataStatus for get all, add a separate property for project status, like `projectStatus`

2024-08-30 18:16 UTC, liza-veis commented on apps/frontend/src/pages/project/project.tsx
> +				<h1 className={styles["project-name"]}>{project?.name}</h1>
let's name it title as in other places
```suggestion
				<h1 className={styles["title"]}>{project?.name}</h1>
```

2024-08-31 11:34 UTC, yevhenii-hladkov commented on apps/frontend/src/pages/project/project.tsx
> +} from "~/libs/hooks/hooks.js";
```suggestion
import { PageLayout } from "~/libs/components/components.js";
import { DataStatus } from "~/libs/enums/enums.js";
import {
	useAppDispatch,
	useAppSelector,
	useParams,
	useEffect,
} from "~/libs/hooks/hooks.js";
```

2024-09-01 15:39 UTC, liza-veis requested changes

2024-09-01 15:39 UTC, liza-veis commented on apps/backend/src/modules/projects/project.controller.ts
> +			params: ProjectGetByIdRequestDto;
let's remove ProjectGetByIdRequestDto, request dto types is only for body payload, not for path parameters. We define parameters explicitly
```suggestion
			params: { id: string };
```

2024-09-02 06:26 UTC, liza-veis approved these changes

2024-09-02 06:26 UTC, merged