fix: The page reloads after generating the API key gf-289
BinaryStudioAcademy/bsa-2024-gitfit pull request #293
Opened 2024-09-12 14:02 UTC by GvoFor

Make the page not reload while/after API key generated

2024-09-12 14:19 UTC, perekotypole commented on apps/frontend/src/modules/project-api-keys/slices/actions.ts
> +	void dispatch(projectActions.updateApiKey(response.apiKey));
What is the point of `updateApiKey` action if it just triggers `state.project.apiKey = action.payload;`  which can be included to `create`? Or am I misunderstanding something?

2024-09-12 20:27 UTC, liza-veis requested changes

2024-09-12 20:27 UTC, liza-veis commented on apps/frontend/src/modules/project-api-keys/slices/actions.ts
> +	void dispatch(projectActions.updateApiKey(response.apiKey));
I think we don't need a separate action for this, we return response in this action, so we can access it inside create.success case in reducer. It's ok if we use action from another module inside projects, just import it the same way as we do for components.

2024-09-13 06:08 UTC, what1s1ove approved these changes

2024-09-13 06:19 UTC, liza-veis approved these changes

2024-09-13 06:19 UTC, merged