feat: Add users column to the groups table gf-301
BinaryStudioAcademy/bsa-2024-gitfit pull request #304
Opened 2024-09-12 18:18 UTC by GvoFor

## Screenshots
![image](https://github.com/user-attachments/assets/527045ea-0143-4fbe-b3d0-ac16bcb63d8b)

2024-09-12 20:17 UTC, liza-veis requested changes

2024-09-12 20:17 UTC, liza-veis commented on apps/frontend/src/pages/access-management/libs/types/group-row.type.ts
> +	users: number;
let's name it userCount for internal fields to make it more clear from the code, but the title for the column will remain "Users"
```suggestion
	userCount: number;
```

2024-09-13 06:09 UTC, what1s1ove approved these changes

2024-09-13 06:18 UTC, liza-veis approved these changes

2024-09-13 06:18 UTC, merged