feat: add script for collecting statistics gf-247
BinaryStudioAcademy/bsa-2024-gitfit pull request #315
Opened 2024-09-13 14:46 UTC by s1rserg

* Created a script for collecting statistics on background.
* The script is a separate app inside main directory.
* The cli command accepts a project repository path, project api key and user id (will be used for created_by in statistics) as parameters and starts a background job.
* Every 3 hours the job fetches the latest changes, collects statistics from remote for the day, and sends a request to update it on the backend.
* For authorization a project API key is used and sent in Bearer format.

## How to run
1. cd scripts
2. cd analytics
3. npm run build
4. node --no-warnings build/index.js run-forever repoPath apiKey userId

## TODO
* Refactor folder structure.
* Refactor and test after merge of #181.

2024-09-14 17:31 UTC, liza-veis requested changes

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/modules/cli/scheduler.ts
> +	cron.schedule(CRON_SCHEDULE, () => {
We need to have a separate module for corn - TaskScheduler (similar to logger)

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/index.ts
> +	.version("1.0.0");
We need a separate module for this logic, similar to server-application on backend as starting point. It should be called like AnalyticsCli or similar and it should init the application

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/modules/cli/libs/helpers/format-date.helper.ts
> +function formatDate(date: Date): string {
we already have formatDate helper in shared, we need to use it and we need to pass needed format instead of writing all this logic manually

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/modules/cli/libs/helpers/get-fetch.helper.ts
We need to create a separate module for working with git, something like GITService. Should be in libs/modules same as logger

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/modules/cli/script.ts
> +async function collectAndSendStats({
This script should be a separate module with methods, like src/modules/analytics (similar to what we have in the backend, but we only will have `.service`).

2024-09-14 17:31 UTC, liza-veis commented on scripts/analytics/src/modules/cli/script.ts
> +const execAsync = promisify(exec);
We need to move exec in helpers

2024-09-16 10:58 UTC, s1rserg commented on scripts/analytics/src/libs/modules/api/libs/types/get-headers-options.type.ts
> +	token?: string | undefined;
It doesn't work like that. I changed it to look like contentType.

2024-09-16 11:12 UTC, what1s1ove approved these changes

2024-09-16 11:12 UTC, what1s1ove commented on package.json
> +		"build:analytics": "npm run build -w scripts/analytics",
but you deleted the built script?

2024-09-16 11:41 UTC, liza-veis requested changes

2024-09-16 11:41 UTC, liza-veis commented on packages/shared/src/modules/activity-logs/libs/validation-schemas/libs/constants/email-regex.constant.ts
> +const EMAIL_REGEX =
We need to name it more specifically so that we understand how it differs from built-in email validation. Does it match emails with github or what?

2024-09-16 11:41 UTC, liza-veis commented on scripts/analytics/src/libs/modules/analytics-cli/base-analytics-cli.ts
> +					return;
Maybe we need to log some error message in this case?

2024-09-16 11:41 UTC, liza-veis commented on scripts/analytics/src/modules/analytics/libs/helpers/execute-command.helper.ts
> +): Promise<{ stderr: Buffer | string; stdout: Buffer | string }> {
use arrow function, and remove options if they are not used for now

2024-09-16 11:41 UTC, liza-veis commented on scripts/analytics/src/libs/modules/task-scheduler/task-scheduler.ts
> +	schedule: CRON_SCHEDULE,
this should be passed as parameters when we start the task
```suggestion
```

2024-09-16 11:41 UTC, liza-veis commented on packages/shared/src/modules/activity-logs/libs/validation-schemas/libs/constants/email-regex.constant.ts
> +const EMAIL_REGEX =
something like GIT_EMAIL_REGEX

2024-09-16 11:41 UTC, s1rserg commented on package.json
> +		"build:analytics": "npm run build -w scripts/analytics",
My bad. I returned it.

2024-09-16 13:25 UTC, s1rserg commented
@liza-veis. There is an issue that I can't fix. When I build the scripts/analytics and then try to run it using node build/index.js ... program gives errors about absence of env variables. Considering the script needed asap, maybe you can point out what's wrong.

2024-09-16 13:30 UTC, liza-veis commented
> @liza-veis. There is an issue that I can't fix. When I build the scripts/analytics and then try to run it using node build/index.js ... program gives errors about absence of env variables. Considering the script needed asap, maybe you can point out what's wrong.

it's ok, this will be fixed when I set up publishing to npm

2024-09-16 13:56 UTC, liza-veis approved these changes

2024-09-16 13:57 UTC, merged