fix: adjusted project status message based on search state gf-313
BinaryStudioAcademy/bsa-2024-gitfit pull request #319
Opened 2024-09-13 19:02 UTC by Fjortis

Modified the logic for displaying the project status message to handle two cases:
  - When no projects have been created: "No projects created yet. Create the first project now."
  - When a search query returns no results: "No projects found matching your search criteria. Please try different keywords."
  
 No Projects
![No message](https://github.com/user-attachments/assets/1d1a5a64-439b-439b-aa71-f4c6ddd02566)
No Projects
![No projects](https://github.com/user-attachments/assets/e300ff1d-bdaa-467b-ab59-218c3c84a614)
With projects
![with proj](https://github.com/user-attachments/assets/0b80b400-4322-46b6-b824-bcc5da4181a9)
With Projects
![with proj no search result](https://github.com/user-attachments/assets/63371b09-7db1-4a99-a148-33700b14c3f8)

2024-09-14 13:27 UTC, liza-veis requested changes

2024-09-14 13:27 UTC, liza-veis commented on apps/frontend/src/pages/projects/projects.tsx
> +	const ProjectStatusMessage = hasSearch
```suggestion
	const emptyPlaceholderMessage = hasSearch
```

2024-09-14 14:20 UTC, Fjortis commented on apps/frontend/src/pages/projects/projects.tsx
> +	const ProjectStatusMessage = hasSearch
Adjusted the naming

2024-09-14 17:32 UTC, liza-veis approved these changes

2024-09-15 16:44 UTC, GvoFor commented on apps/frontend/src/pages/projects/projects.tsx
> +	const emtyPlaceholderMessage = hasSearch
```suggestion
	const emptyPlaceholderMessage = hasSearch
```

2024-09-16 09:14 UTC, Fjortis commented on apps/frontend/src/pages/projects/projects.tsx
> +	const emtyPlaceholderMessage = hasSearch
Nice catch buddy 👍

2024-09-16 11:12 UTC, what1s1ove approved these changes

2024-09-16 11:12 UTC, merged