feat: add sign in flow gf-7
BinaryStudioAcademy/bsa-2024-gitfit pull request #36
Opened 2024-08-19 14:24 UTC by perekotypole

Implemented backend sign-in flow:

- add methods to find user in user service
- /auth/sing-in returns user (without password) on correct email 

To do:

- connect encryption service to compare passwords (needs ticket 6)
- add changes given by token implementation

2024-08-20 07:44 UTC, perekotypole commented on apps/backend/src/modules/users/user.service.ts
> +				message: "User doesn't exist",
Should it be common? Or is it better to specify it to user module?

2024-08-20 09:15 UTC, liza-veis commented on apps/backend/src/modules/users/user.service.ts
> +				message: "User doesn't exist",
We might have the same exception messages across different services or apps (backend/frontend). Usually, it is not directly linked to the service but more to the domain. It's not the only right way to do this, more like a stylistic question and that's the way we prefer in this project

2024-08-20 09:56 UTC, perekotypole commented on packages/shared/src/modules/users/libs/exceptions/user-error.exception.ts
> +import { type ValueOf } from "../../../../libs/types/value-of.type.js";
We don't have typescript paths for shared, so we decided to leave this as it is

2024-08-21 05:46 UTC, what1s1ove approved these changes

2024-08-21 06:09 UTC, yevhenii-hladkov approved these changes

2024-08-21 07:30 UTC, perekotypole commented
@liza-veis conflicts are fixed

2024-08-21 08:30 UTC, liza-veis requested changes

2024-08-21 08:30 UTC, liza-veis commented on apps/backend/src/modules/users/user.service.ts
> +	private encryption: BaseEncryption;
we should use `Encryption`, we need to export it from  `~/libs/modules/encryption/encryption.js`

```suggestion
	private encryption: Encryption;
```

2024-08-21 12:59 UTC, liza-veis approved these changes

2024-08-21 13:28 UTC, merged