fix: useSearch change to handle modal search inputs gf-455
BinaryStudioAcademy/bsa-2024-gitfit pull request #459
Opened 2024-09-20 14:46 UTC by Fjortis

Improved flexibility: Allows the search functionality to be tailored for various contexts (e.g., modal or page search) without hardcoding specific behaviors.

2024-09-20 15:02 UTC, Fjortis commented
I am unsure about this change, perhaps it is better to make use of useState and useAppForm for modals instead of using useSearch. Do you think this is a better way of doing it?

2024-09-20 15:03 UTC, perekotypole commented on apps/frontend/src/libs/hooks/use-search/use-search.hook.ts
> +): {
I think it's better to pass an argument as an object, useSeatch(false) doesn't look very clear. 
And don't forget about B19 (now naming is the same as hooks)

2024-09-20 17:32 UTC, liza-veis requested changes

2024-09-20 17:32 UTC, liza-veis commented on apps/frontend/src/pages/access-management/libs/components/group-users-table/group-users-table.tsx
> +	const { onSearch, search } = useSearch({ shouldUseQuery: false });
let's rename it to isSavedToUrl
```suggestion
	const { onSearch, search } = useSearch({ isSavedToUrl: false });
```

2024-09-20 17:32 UTC, liza-veis commented on apps/frontend/src/libs/hooks/use-search/use-search.hook.ts
> +type SearchOptions = {
```suggestion
type Parameters = {
```

2024-09-20 17:35 UTC, what1s1ove approved these changes
lgtm after Lisa's changes

2024-09-21 12:37 UTC, liza-veis approved these changes

2024-09-21 12:37 UTC, merged