docs: requirements update 2.3 Auth gf-63
BinaryStudioAcademy/bsa-2024-gitfit pull request #97
Opened 2024-08-26 13:46 UTC by VeronikaHordus

- Add fields validation information
- Add info about Hide/Show password toggle
- All changes updated regarding to the suggestions received before

2024-08-26 15:58 UTC, liza-veis approved these changes

2024-08-27 11:31 UTC, what1s1ove approved these changes

2024-08-27 17:16 UTC, RemeslovaOksana requested changes

2024-08-27 17:16 UTC, RemeslovaOksana commented on docs/specification.md
> +- at least 3 characters;
Max characters?

2024-08-27 17:16 UTC, RemeslovaOksana commented on docs/specification.md
> +
Max characters?

2024-08-29 06:10 UTC, merged