docs: requirement update access managment gf-64
BinaryStudioAcademy/bsa-2024-gitfit pull request #99
Opened 2024-08-26 14:37 UTC by VeronikaHordus

- add page access details
- describ page appearance for users with no certain permission
- add field validation info

2024-08-27 11:31 UTC, what1s1ove approved these changes

2024-08-27 20:36 UTC, RemeslovaOksana requested changes

2024-08-27 20:36 UTC, RemeslovaOksana commented on docs/specification.md
> +- “Name” field. Validation: Field should not be empty.
only letters or numbers and special characters too? maximum characters?

2024-08-28 18:46 UTC, RemeslovaOksana approved these changes

2024-08-29 06:11 UTC, merged